### ISSUE TITLE
Question: adding additional cities

### ISSUE THREAD

**Issue by newswim** [mckeever02/tryingtowork#1]
Hey this site is great!

I'd like to do something similar for my city, and I'm curious if there's any desire on the part of the author to incorporate more cities into the site (since this would just require adding records for coffee shops and maybe an 'additional cities' dropdown somewhere).

Or alternatively, would you be interested in listing additional cities somewhere on the page, and letting other devs fork the site to customize and build up their own listings? That might be more inline with the original intent of the project.

Curious if you have thoughts on this, thanks again and congrats for the good work!

🎆 🎆 🎆 🎆

**Comment by mckeever02** [comment]
Hi newswim, sorry for the super delayed reply. I've just rebuilt and relaunched this. https://tryingtowork.in/

But to answer your question: Yes! I would love to add more cities. If you could submit 3 or more spaces from your city (using the modal form on the site) I will add your city to the site. :-)

Let me know if you've any questions
