### ISSUE TITLE
Opening times are off

### ISSUE THREAD

**Issue by jdillard** [mckeever02/tryingtowork#2]
In this blog post you mention "dynamically" showing the opening times using liquid: 

https://mckvr.com/jekyll/liquid/2017/05/15/displaying-opening-times-in-jekyll/

With this approach aren't the times only true at the time of the last build? For this to be truly dynamic, wouldn't you want that logic in javascript. Maybe use liquid to generate a json list of locations, then use the filter function to get the desired results.

**Comment by mckeever02** [comment]
Sorry for the super long reply but I've now rebuilt and relaunched this. Opening times are now pulled in from Google places: https://tryingtowork.in/
